### PR TITLE
swap description and long description

### LINKED ISSUE #119: "summary" and "description" fields on pypi should be switched around
A package's summary should be a short one-liner which gives people an idea what the package is about. However, when you do `pip search doctr`, you get a unreadable wall of text, with the formatting broken and the newlines removed. The wall of text should go into the `description` field, which preserves the formatting.

### PR DESCRIPTION
**Pull request by gforsyth**
Resolves #119

### CODE REVIEW

**Comment by asmeurer** [comment]
It's that damn test again. Maybe we should revert that PR.

**Comment by gforsyth** [comment]
Ok, I restarted the test and it passed this time.  Maybe just a weird github API thing again?  Or are we hitting some limits for unauthorized clients?  I'm ok reverting the tests if they continue to cause trouble.

**Comment by asmeurer** [comment]
Looks better now https://pypi.python.org/pypi/doctr

**Comment by gforsyth** [comment]
That looks *much* better.

**Comment by asmeurer** [comment]
:)

**Pull request merged**
