### PR TITLE
add xonsh to readme

### PR DESCRIPTION
**Pull request by scopatz**

### CODE REVIEW

**Comment by asmeurer** [comment]
@gforsyth you might want to look at the test failure. Travis is giving a PNG instead of JSON?

**Comment by gforsyth** [comment]
Weeeeirrdddd. So yeah, now if you try to ping an invalid user or repo instead of JSON you get this badge: 
badge

so I guess I can change the test to see if we get JSON back at all, rather than examining the status codes

**Comment by asmeurer** [comment]
Seems like a bug in Travis. Might want to open an issue with them to see if it's a regression. IMO api.* sites shouldn't return non-JSON.

**Comment by gforsyth** [comment]
Thanks, @scopatz!

**Comment by scopatz** [comment]
Sorry it was such a rabbit hole.

**Comment by gforsyth** [comment]
No worries -- it was going to pop up sooner or later!

**Pull request merged**
