### PR TITLE
Run --command on the original branch, not the deploy branch

### PR DESCRIPTION
**Pull request by asmeurer**
Fixes https://github.com/drdoctr/doctr/issues/191

### CODE REVIEW

**Comment by asmeurer** [comment]
Looks like it is working.

**Comment by gforsyth** [comment]
Looks good, sorry for the delay @asmeurer

**Comment by asmeurer** [comment]
This actually breaks the SymPy use of doctr, which relies on running a script in the deploy repo (separate from the main repo). Going to revert for now and do a bugfix release. I didn't end up needing my original use for this, so I'll probably just leave it as an open issue to be able to run --command in the original repo.

**Comment by asmeurer** [comment]
Actually a little complicate to do this. I'm going to try a workaround where I pull in the script from `doctr_remote/gh-pages` using gh-pages before running it.  If it works, we should document it.

**Comment by asmeurer** [comment]
Oh that doesn't work. It needs the files from the deploy repo. I guess we should have a --pre-command and a --post-command.

**Comment by asmeurer** [comment]
OK, I actually don't think a pre-checkout command (what --command does in 1.6) is useful. If you want to run a command before anything, just run it in the build before you run doctr.

**Pull request merged**
