### PR TITLE
Add and remove all the files in one git command

### LINKED ISSUE #324: doctr with lots of files in docs
So we sucessfully set up doctr to generate the documentation for statsmodels. Cool tool, I like it. 

However, statsmodels generates lots, and lots, and lots of files for itss docs. 

It looks like doctr is taking about 20 minutes to cycle through the `git add file` here:

https://github.com/drdoctr/doctr/blob/5067c1e28ef446ef058157bce2441554a2710588/doctr/travis.py#L477-L482

Any ideas how to speed this up?

### PR DESCRIPTION
**Pull request by asmeurer**
This might fix #324.

### CODE REVIEW

**Comment by asmeurer** [comment]
This ran pretty quick for me adding 10000 empty files.

**Comment by asmeurer** [comment]
And I can confirm my test is slower the old way, even though they're empty files, by about a minute and a half. https://travis-ci.org/drdoctr/doctr/jobs/430365436. 

@thequackdaddy can you try running your build against this branch (install doctr from this branch)?

**Comment by asmeurer** [comment]
Or I can try it out myself tomorrow if you don't get to it.

**Comment by thequackdaddy** [comment]
Nice. You shaved 25 minutes off the build!

https://travis-ci.org/thequackdaddy/statsmodels/jobs/430370425

**Comment by asmeurer** [comment]
Awesome. We should still figure out how to only add the changed files to shorten the output size in the log, but I'll leave that for a future PR.

**Comment by thequackdaddy** [comment]
Thanks for the fast turnaround on this. 

Do you plan to release to pypi soon? Otherwise, I will make a PR on statsmodels to install from master here.

**Pull request merged**
