### PR TITLE
Update travis yml

### PR DESCRIPTION
**Pull request by gforsyth**
An attempt to address #104 -- this was harder than I thought.

I tried to cover all the situations I could think of re: which fields might have already been defined or not in someone's `.travis.yml`. 

One issue (which may be a deal breaker) it doesn't preserve newlines for multiline yaml blocks -- I have it configured so that when those lines are rewritten (after round trip parsing) that they are still valid (basically, put them all on one line) but maybe it's better to warn people before we do that and ask them if it's ok?

### CODE REVIEW

**Comment by asmeurer** [comment]
What's the deal with the newlines? The round-trip parser doesn't handle them?

**Comment by asmeurer** [comment]
Looks exciting. Maybe we could test it out on some real life .travis.ymls. [SymPy's](https://github.com/sympy/sympy/blob/master/.travis.yml) is pretty complicated.

**Comment by asmeurer** [comment]
What does this do if there's already an encrypted variable in the file?

**Comment by gforsyth** [comment]
The round trip parser doesn't seem to recognize semi-colons as valid line endings -- or rather, it correctly recognizes a semi-colon separated line or lines as being a single yaml directive, so it groups them together.  When it writes back to a file, it doesn't preserve the newlines after the semicolons, but just writes them all to one line -- so, for instance, the `if DOCS` logic in our `.travis.yml` will be condensed to a single long line. 

I'm curious to see how it handles SymPy's travis.yml -- if that works, then I'm comfortable with the logic (pending some kind of warning about the newline removal).

If there's already a an encrypted variable, this will just add another one after it, so something like

```console
env:
  global:
    - secure: gobbledy-gook
    - secure: more-gobbledy-gook
```

If it's the _same_ encrypted variable name, I imagine the second one will overwrite the first?  I'm not sure about that but it shouldn't be too difficult to confirm that.

**Comment by asmeurer** [comment]
Well often (but not always) an existing secure variable means that the old one was a previous doctr environment variable (there's no way to tell). So we should maybe warn the user. Also, since the variable is gobbleddy-gook, should we add a comment stating what the variable is?

**Comment by gforsyth** [comment]
Ok -- if there's already a secure variable in the .travis.yml then a warning is issued.  Something to the effect that we're appending a new one to the list of global secure variables and this could potentially overwrite something in the environment.
Also now adds a comment with the current date when the key is added so people know which key belongs to doctr (from now on).

I tested it on sympy's `.travis.yml` and that exposed some issues which I've fixed regarding block indentations etc. Now I think it works, even on that monster. Note, though, that there's a significant diff when I run it on sympy's travis.yml since a bunch of the indentation is changed (although not the physical blocks, just the spacing). This could potentially be annoying, but it shouldn't _break_ anything.

**Comment by asmeurer** [comment]
Yeah, that is annoying. I guess ruamel isn't as round-trippy as we would have hoped?

**Comment by gforsyth** [comment]
Apparently not? The documentation is well nigh nonexistent, so there's possibly some way to do it that I've missed.  I'm not quite ready to give up on this -- at the very least, we could offer to do it with a warning that it might screw around with indentation

**Comment by asmeurer** [comment]
Well it's your call, but personally I think adding a bunch of random whitespace to .travis.yml would be very annoying. As a user, I'd probably rather it just not try to edit it at all if it does that.

**Comment by gforsyth** [comment]
I'm going to close this out since the round-trip parser doesn't seem to be in a state to do this cleanly.

**Comment by asmeurer** [comment]
That's too bad. I'd really like to see this feature.

**Pull request closed without merging**
