### PR TITLE
Don't attempt to push gh-pages to the remote if canpush=False

### LINKED ISSUE #145: auth issue when creating gh-pages branch
`travis.create_gh_pages` creates an orphan `gh-pages` branch with a `.nojekyll` file but it can't push this to the remote unless it's authenticated.

if there is no `gh-pages` branch then doctr will return a nonzero exit code when built on a PR since `canpush` will be set to `False`.

probably can just wrap all of the creation stuff in an `if canpush` block

### PR DESCRIPTION
**Pull request by asmeurer**
Fixes #145.

We need to test this somehow. I guess I'll create an empty dummy repo that has no gh-pages branch and try to setup doctr on it from a PR.

### CODE REVIEW

**Comment by asmeurer** [comment]
I've done a test of this [here](https://github.com/drdoctr/test/pull/1). It seems to fix the issue.

**Comment by asmeurer** [comment]
@gforsyth between this fix and https://github.com/drdoctr/doctr/pull/147 we should do a release. Any other changes you want to get in first?

**Comment by gforsyth** [comment]
Hey @asmeurer -- I don't think so.  Obviously I'd like 2FA to be working again, but we can always do another release once that's sorted out. This looks good -- just waiting on CI before merging.

**Comment by asmeurer** [comment]
It would be nice to figure out https://github.com/drdoctr/doctr/issues/148 but if my assesment is correct (and I'm not 100% sure it is) it could require a bit of work.

**Comment by gforsyth** [comment]
Yeah -- I took a quick look at the docs link you posted.  Just finished teaching a workshop I was helping to run this week, so hopefully I'll have a little more time this weekend to dig into it.

**Pull request merged**
