### PR TITLE
Building wikis and multiple deploy repos

### LINKED ISSUE #275: Support GitHub wikis
GitHub wikis are backed by a git repository (e.g., https://github.com/drdoctr/doctr.wiki.git). I haven't checked, but assuming a deploy key allows pushing to a wiki, we should add support for it. This would likely just be detecting if the repo name ends in `.wiki` and stripping it when uploading the key in doctr configure.

### PR DESCRIPTION
**Pull request by asmeurer**
This is based on https://github.com/drdoctr/doctr/pull/276. I needed to push a branch up to the main repo to test the multiple deploy keys. 

Fixes #275 and #242.

### CODE REVIEW

**Comment by asmeurer** [comment]
OK, the push to the second repo failed. Any thoughts? Is the original token for drdoctr/doctr confusing it?

**Comment by asmeurer** [comment]
Ah it's failing because of the `doctr` configuration in Travis, which overrides the flags. 

We want to test that the automatic flags work, though, so I'm going to remove it.

**Comment by asmeurer** [comment]
Cool, the multiple deploy keys work https://drdoctr.github.io/docs-wiki/ https://github.com/drdoctr/drdoctr.github.io. 

So now we just need to test the wiki. I'll probably try that tomorrow. We just need to add a test build to .travis.yml that pushes some test file to the doctr wiki.

**Comment by ylemkimon** [comment]
Shouldn't command line arguments override yaml configs?

**Comment by asmeurer** [comment]
Wiki deploy works https://github.com/drdoctr/doctr/wiki/deploy-test

**Comment by asmeurer** [comment]
OK, I want to update the docs. I might also try to get https://github.com/drdoctr/doctr/pull/225 merged, so we can include all the major changes in a 1.7 release.

**Pull request merged**
