### PR TITLE
Add link to GH docs on branch protection

### PR DESCRIPTION
**Pull request by willingc**

### CODE REVIEW

**Comment by asmeurer** [comment]
Argh. It looks like I somehow broke Travis tests on PRs from forks. Let me see if I can fix it.

**Comment by asmeurer** [comment]
@willingc can you click the "update with master" button?

**Comment by asmeurer** [comment]
Thanks for the patch. And I wouldn't have noticed that really bad bug as quickly if it weren't for this (though I really should have noticed it last night).

**Comment by willingc** [comment]
Glad to be of service ;-) @carreau mentioned the project to me yesterday. I like it 👍

**Comment by asmeurer** [comment]
Thanks. Would be happy to hear any feedback you have if you use it.

**Pull request merged**
