### PR TITLE
Add a global table of contents to the docs sidebar

### PR DESCRIPTION
**Pull request by asmeurer**
This fixes https://github.com/drdoctr/doctr/issues/231. If we find a better theme, we can use it, but this is the main thing I wanted.

### CODE REVIEW

**Comment by ylemkimon** [comment]
It seems local toc and global toc have the same name.

**Comment by asmeurer** [comment]
I'm not following. 

I added both to `index` becaause for some reason the global toc doesn't include the local toc there (it works on every other page).

**Comment by ylemkimon** [comment]
toc

**Comment by asmeurer** [comment]
I see what you mean. I'll have to see if that's configurable.

**Comment by asmeurer** [comment]
It seems there is not a good way to include `index` itself in the global toc (see https://github.com/sphinx-doc/sphinx/issues/2103). But I think we can achieve the effect by copying the templates for the tocs and modifying them.

**Comment by asmeurer** [comment]
I think I found a reasonable solution at https://github.com/drdoctr/doctr/pull/285 (see https://drdoctr.github.io/doctr/docs-release/). It isn't perfect but it's better (see the commit message of https://github.com/drdoctr/doctr/pull/285/commits/c8096abb12ea718eb9deb2b6416c5c9df652d355).

**Pull request merged**
