### PR TITLE
Run --command with shell=True

### PR DESCRIPTION
**Pull request by asmeurer**
This is what most users will expect, and without this running more than one
command would require creating a script file.

Will have merge conflicts once https://github.com/drdoctr/doctr/pull/192 is merged.

### CODE REVIEW

**Comment by asmeurer** [comment]
Looks like it is working. I wanna do a release once this and #192 are in.

**Comment by gforsyth** [comment]
Conflicts on this now

**Comment by asmeurer** [comment]
Merged in master, and double checked that it still works.

**Comment by gforsyth** [comment]
Looks good.  Thanks, @asmeurer !

**Pull request merged**
