### PR TITLE
Fix repo check

### LINKED ISSUE #107: Repo check fails for forks
We should probably be using [this api](https://developer.github.com/v3/repos/) to check if a repo exists.

### PR DESCRIPTION
**Pull request by asmeurer**
The search doesn't find forks. This removes the distinction between a wrong
user and a wrong repo, but I think that's fine.

Fixes #107.

### CODE REVIEW

**Comment by asmeurer** [comment]
Don't know why that's failing intermittently.

**Comment by asmeurer** [comment]
But I think it doesn't work on forks anyway (https://github.com/drdoctr/doctr/issues/110). So maybe we can keep the existing check but change the error message. I'm not sure what to do here.

**Comment by asmeurer** [comment]
And it passed this time. Still, and intermittent failure like that is no good. But maybe it was an issue on GitHub's side?

**Comment by gforsyth** [comment]
Hey @asmeurer , I'm back in the world.  I just triggered a rebuild -- I think if that works then we can chalk it up as a (resolved) github issue?

**Comment by asmeurer** [comment]
I guess it's a GitHub issue. If the API were wrong it wouldn't work at all.

**Comment by gforsyth** [comment]
Ok, merging this

**Pull request merged**
